Repository iluwatar/java-design-patterns, pull requests merged in 2024-03, with the labels that each got.

#2629 #392 added Notification Pattern
  notification/README.md
  notification/etc/notification.urm.png
  notification/etc/notification.urm.puml
  notification/pom.xml
  notification/src/main/java/com/iluwatar/App.java
  notification/src/main/java/com/iluwatar/DataTransferObject.java
  notification/src/main/java/com/iluwatar/Notification.java
  notification/src/main/java/com/iluwatar/NotificationError.java
  notification/src/main/java/com/iluwatar/RegisterWorker.java
  notification/src/main/java/com/iluwatar/RegisterWorkerDto.java
  notification/src/main/java/com/iluwatar/RegisterWorkerForm.java
  notification/src/main/java/com/iluwatar/RegisterWorkerService.java
  notification/src/main/java/com/iluwatar/ServerCommand.java
  notification/src/test/java/com/iluwatar/AppTest.java
  notification/src/test/java/com/iluwatar/RegisterWorkerFormTest.java
  notification/src/test/java/com/iluwatar/RegisterWorkerTest.java
  pom.xml
Labels: status: under review, status: stale

#2726 docs : Translate the Visitor to Korean
  localization/ko/visitor/README.md
  localization/ko/visitor/etc/visitor_1.png
Labels: status: stale

#2734 feature: Add gateway pattern (#1297)
  gateway/README.md
  gateway/etc/gateway.urm.png
  gateway/etc/gateway.urm.puml
  gateway/pom.xml
  gateway/src/main/java/com/iluwatar/gateway/App.java
  gateway/src/main/java/com/iluwatar/gateway/ExternalServiceA.java
  gateway/src/main/java/com/iluwatar/gateway/ExternalServiceB.java
  gateway/src/main/java/com/iluwatar/gateway/ExternalServiceC.java
  gateway/src/main/java/com/iluwatar/gateway/Gateway.java
  gateway/src/main/java/com/iluwatar/gateway/GatewayFactory.java
  gateway/src/test/java/com/iluwatar/gateway/AppTest.java
  gateway/src/test/java/com/iluwatar/gateway/ServiceFactoryTest.java
Labels: status: under review

#2777 anti corruption layer - Issue 1325.
  anti-corruption-layer/README.md
  anti-corruption-layer/etc/anti-corruption-layer.urm.puml
  anti-corruption-layer/pom.xml
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/App.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/package-info.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/AntiCorruptionLayer.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/DataStore.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/ShopException.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/legacy/LegacyOrder.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/legacy/LegacyShop.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/legacy/LegacyStore.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/modern/Customer.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/modern/ModernOrder.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/modern/ModernShop.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/modern/ModernStore.java
  anti-corruption-layer/src/main/java/com/iluwatar/corruption/system/modern/Shipment.java
  anti-corruption-layer/src/main/resources/application.properties
  anti-corruption-layer/src/test/java/com/iluwatar/corruption/system/AntiCorruptionLayerTest.java
  pom.xml
Labels: status: under review

#2733 Finished Explanation for Leader/Followers #2239
  leader-followers/README.md
Labels: status: under review

#2731 Update README.md for Monostate design pattern
  monostate/README.md
Labels: status: under review

#2795 Implemenation of the Serialized Lob Pattern
  pom.xml
  slob/README.md
  slob/etc/slob.urm.png
  slob/etc/slob.urm.uml
  slob/pom.xml
  slob/src/main/java/com/iluwatar/slob/App.java
  slob/src/main/java/com/iluwatar/slob/dbservice/DatabaseService.java
  slob/src/main/java/com/iluwatar/slob/lob/Animal.java
  slob/src/main/java/com/iluwatar/slob/lob/Forest.java
  slob/src/main/java/com/iluwatar/slob/lob/Plant.java
  slob/src/main/java/com/iluwatar/slob/serializers/BlobSerializer.java
  slob/src/main/java/com/iluwatar/slob/serializers/ClobSerializer.java
  slob/src/main/java/com/iluwatar/slob/serializers/LobSerializer.java
  slob/src/test/java/com/iluwatar/slob/AppTest.java
Labels: status: under review

#2652 Update README.md
  half-sync-half-async/README.md
Labels: status: under review
